apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator-certified
  namespace: openshift-operators
spec:
  channel: stable
  name: seldon-operator-certified
  installPlanApproval: Manual
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.7.0

