apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linedataserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://{{ .Values.git.provider }}/{{ .Values.git.account }}/blueprint-elements-library.git
    targetRevision: HEAD
    path: manufacturing-edge-ai-ml/factory/sites/{{ .Values.site.name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
