kind: Secret
apiVersion: v1
metadata:
  name: github
type: Opaque
data:
  # Go to: https://github.com/settings/tokens
  # Then: echo -n 'your string value' | base64
  token: {{ .Values.git.authToken }}
  user: {{ .Values.git.accountToken }}

