---
# Source: manuela/templates/argocd-factorydatacenter.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorydatacenter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dagger-refuse-cool/blueprint-elements-library.git
    targetRevision: HEAD
    path: manufacturing-edge-ai-ml/factory/sites/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
---
# Source: manuela/templates/argocd-linedataserver.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linedataserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dagger-refuse-cool/blueprint-elements-library.git
    targetRevision: HEAD
    path: manufacturing-edge-ai-ml/factory/sites/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
---
# Source: manuela/templates/channel-sensors.yaml
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: manuela-mcs-gitops-channel-sensors
  namespace: manuela-sensors-mcs
spec:
  pathname: https://github.com/dagger-refuse-cool/blueprint-elements-library.git
  type: Git
---
# Source: manuela/templates/klusterlet.yaml
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  clusterName: wh-factory-org
